name: Publish to Maven Central

on:
  release:
    types: [published] # Trigger on new release publication

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        id: secrets-check
        run: |
            if [ -z "${{ secrets.SONATYPE_USERNAME }}" ]; then echo "❌ SONATYPE_USERNAME not set"; else echo "✅ SONATYPE_USERNAME set"; fi
            if [ -z "${{ secrets.SONATYPE_PASSWORD }}" ]; then echo "❌ SONATYPE_PASSWORD not set"; else echo "✅ SONATYPE_PASSWORD set"; fi
            if [ -z "${{ secrets.PGP_SECRET }}" ]; then echo "❌ PGP_SECRET not set"; else echo "✅ PGP_SECRET set"; fi
            if [ -z "${{ secrets.PGP_PASSPHRASE }}" ]; then echo "❌ PGP_PASSPHRASE not set"; else echo "✅ PGP_PASSPHRASE set"; fi

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "SONATYPE_USERNAME is set: ${{ secrets.SONATYPE_USERNAME != '' }}"
          echo "SONATYPE_PASSWORD is set: ${{ secrets.SONATYPE_PASSWORD != '' }}"
          echo "PGP_SECRET is set: ${{ secrets.PGP_SECRET != '' }}"
          echo "PGP_PASSPHRASE is set: ${{ secrets.PGP_PASSPHRASE != '' }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Set up GPG
        run: |
          echo "$PGP_SECRET" | base64 --decode | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Release
        run: sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
