name: Publish to Maven Central

on:
  release:
    types: [published] # Trigger on new release publication

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        id: secrets-check
        run: |
          if [[ -z "${{ secrets.SONATYPE_USERNAME }}" || -z "${{ secrets.SONATYPE_PASSWORD }}" || -z "${{ secrets.PGP_SECRET_KEY }}" || -z "${{ secrets.PGP_PASSPHRASE }}" ]]; then
            echo "Missing one or more required secrets. Skipping publish."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "All required secrets found."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if secrets are missing
        if: steps.secrets-check.outputs.skip == 'true'
        run: |
          echo "Required secrets not found. Exiting workflow."
          exit 0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Set up GPG
        run: |
          echo "$PGP_SECRET" | base64 --decode | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET_KEY }}

      - name: Release
        run: sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
